### ISSUE TITLE
/proc/self/uid_map: no such file or directory

### ISSUE THREAD

**Issue by gbmeuk** [joyent/sdc-vmtools-lx-brand#28]
Hi,

Sorry if this is the wrong repo but it's not clear to me, from searching, where would be and this seemed like a good place to start to be redirected to the correct place.

I've been trying to run [Concourse](http://concourse.io) on Triton and hit an issue where there is no uid_map (and probably gid_map) files in /proc. I understand on Triton that this isn't ever going to be a thing. However, I do wonder whether there should be some stub code for them?

```
panic: open /proc/self/uid_map: no such file or directory

goroutine 1 [running]:
panic(0xd24700, 0xc4201d78c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
code.cloudfoundry.org/guardian/sysinfo.must(0x0, 0xf22f700, 0xc4201d78c0, 0xf22f700)
        /tmp/build/9674af12/garden-runc-release/src/code.cloudfoundry.org/guardian/sysinfo/max_valid_uid.go:69 +0x66
code.cloudfoundry.org/guardian/sysinfo.MustGetMaxValidUID(0xd39e00)
        /tmp/build/9674af12/garden-runc-release/src/code.cloudfoundry.org/guardian/sysinfo/max_valid_uid.go:15 +0x58
code.cloudfoundry.org/guardian/guardiancmd.init.1()
        /tmp/build/9674af12/garden-runc-release/src/code.cloudfoundry.org/guardian/guardiancmd/command.go:225 +0x37
code.cloudfoundry.org/guardian/guardiancmd.init()
        /tmp/build/9674af12/garden-runc-release/src/code.cloudfoundry.org/guardian/guardiancmd/seccomp.go:1598 +0x349
main.init()
        /tmp/build/9674af12/gopath/src/github.com/concourse/bin/cmd/concourse/worker_unix.go:24 +0xdf
```

**Comment by chorrell** [comment]
Hi,

You should probably raise the issue here: https://github.com/joyent/smartos-live

**Comment by gbmeuk** [comment]
Thanks
